package net.pj.games.eulerproject;

import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * <H1>Even Fibonacci numbers</H1>
 * <H2>Problem 2</H2>
 * <p>
 * Each new term in the Fibonacci sequence is generated by adding 
 * the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * <br/>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <br/>
 * By considering the terms in the Fibonacci sequence whose values do not exceed 
 * four million, find the sum of the even-valued terms.
 * </p>
 * 
 * @author dauvertpj
 */
public class Euler002TestSuite {

	private static final Logger log = LoggerFactory.getLogger(Euler002TestSuite.class);	

        @Test
	public void solution() {
            
            log.info("----  Solution of problem 2   ----");
            int maxNumber = 4000000;
            int result=0;
            int fibom = 1;
            int fiboM = 2;
            while(fiboM < maxNumber){
                if(fiboM%2==0){
                    result+=fiboM;
                }
                int current=fiboM;
                fiboM+=fibom;
                fibom=current; 
            }

            log.info("result = {}", result);
        }



}
