package net.pj.games.eulerproject;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * <H1>Distinct Powers</H1>
 * <H2>Problem 29</H2>
 * <p>
 * Consider all integer combinations of a^b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
 * <br/>
 * 2^2=4, 2^3=8, 2^4=16, 2^5=32
 * <br/>
 * 3^2=9, 3^3=27, 3^4=81, 3^5=243
 * <br/>
 * 4^2=16, 4^3=64, 4^4=256, 4^5=1024
 * <br/>
 * 5^2=25, 5^3=125, 5^4=625, 5^5=3125
 * <br/>
 * If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
 * <br/>
 * 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
 * <br/>
 * How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
 * </p>
 *
 * @author dauvertpj
 */
public class Euler029TestSuite {

    private static final Logger log = LoggerFactory.getLogger(Euler029TestSuite.class);

    @Test
    @Ignore
    public void testWhatever() {
        log.info("----  Test for problem 29 ----");
    }

    @Test
    public void solution() {
        log.info("----  Solution of problem 29   ----");
        int result = 0;

        log.info("result = {}", result);
        Assert.assertEquals(0, result);
    }

}
